cmake_minimum_required(VERSION 3.10)

enable_testing()
function(BUILD_TEST)
	set(list_args "${ARGN}")
	list(GET list_args 0 exec_name)
	file(GLOB exec_sources  true *.h *.cpp *.hpp *.c)
	add_executable(${exec_name} ${exec_sources})
	target_include_directories(${exec_name} PUBLIC ./)
	set(list_args "${list_args};gtest;gmock;gtest_main;gmock_main")	
	target_link_libraries(${list_args})
	add_test(NAME ${exec_name} COMMAND ${exec_name})
endfunction()
